[window]

#opacity = 0.82

padding.x = 10
padding.y = 10


decorations = "Full"
decorations_theme_variant = "Light" # "Dark"

[font]

size = 13
[font.normal]
family = "Iosevka Nerd Font"
style = "SemiBold"

[font.bold]
family = "Iosevka Nerd Font"
style = "SemiBold"

# # Colors
# [colors.primary]
# background = "#1a1b26"
# foreground = "#c0caf5"
#
# [colors.cursor]
# text = "#1a1b26"
# cursor = "#c0caf5"
#
# [colors.normal]
# black = "#15161e"
# red = "#f7768e"
# green = "#9ece6a"
# yellow = "#e0af68"
# blue = "#7aa2f7"
# magenta = "#bb9af7"
# cyan = "#7dcfff"
# white = "#a9b1d6"
#
# [colors.bright]
# black = "#414868"
# red = "#f7768e"
# green = "#9ece6a"
# yellow = "#e0af68"
# blue = "#7aa2f7"
# magenta = "#bb9af7"
# cyan = "#7dcfff"
# white = "#c0caf5"
